language: rust
rust:
  - stable

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

script:
  - cargo test --verbose
  - cargo test --verbose --release
  - cargo test --verbose --features "map"
  - cargo test --verbose --release --features "map"