[package]
name = "asn1_der"
version = "0.5.0"
authors = ["KizzyCode Software Labs./Keziah Biermann <development@kizzycode.de>"]
description = "This library provides a simple ASN.1-DER en-/decoder"
license = "BSD-2-Clause OR MIT"
repository = "https://github.com/KizzyCode/asn1_der"
readme = "README.md"

[dependencies]
etrace = { git = "https://github.com/KizzyCode/etrace" }